server:
  port: 8081
spring:
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://vuondau-keycloak.amazingtech.vn/auth/realms/vuondau-application


moodle:
  baseUri: http://moodle-vuondau.amazingtech.vn/webservice/restful/server.php/
  courseUri: http://moodle-vuondau.amazingtech.vn/webservice/restful/server.php/core_course_get_courses
  createCourseUri: http://moodle-vuondau.amazingtech.vn/webservice/restful/server.php/core_course_create_courses
  resourceUri: http://moodle-vuondau.amazingtech.vn/webservice/restful/server.php/core_course_get_contents
  categoryUri: http://moodle-vuondau.amazingtech.vn/webservice/restful/server.php/core_course_get_categories
  createCategoryUri: http://moodle-vuondau.amazingtech.vn/webservice/restful/server.php/core_course_create_categories
  courseContentUri: http://moodle-vuondau.amazingtech.vn/webservice/restful/server.php/core_course_get_contents
  token: c60c932ed4585b4534362b56045e653d


