server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://103.173.255.39:3306/vuondau
    username: root
    password: test
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://vuondau-keycloak.amazingtech.vn/auth/realms/dev
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 10MB
      file-size-threshold: 2KB
      max-file-size: 5MB
minio:
  bucket: requestformstudent
  url: http://103.173.255.39:9000
  access-key: mGUnihw7IeJ3C6EQ
  secret-key: KLXCOA4g71xV5SChU3f278AYH3HqKE7I



management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
# Keycloak settings
keycloak:
  realm: dev
  resource: admin-spring-boot
  app-client: employee-service
  auth-server-url: http://vuondau-keycloak.amazingtech.vn/auth
  credentials:
    secret: EJlhzOe84TZJhy41J3GhEg0yhaXzQuJL