server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/vuondau
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://vuondau-keycloak.amazingtech.vn/auth/realms/dev


