server:
  port: 8081
spring:
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://vuondau-keycloak.amazingtech.vn/auth/realms/vuondau-application


moodle:
  baseUri: http://moodle-vuondau.amazingtech.vn/webservice/restful/server.php/core_course_create_courses
