
spring:
  datasource:
    url: jdbc:mysql://103.173.255.39:3306/vuondau
    username: root
    password: test
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://vuondau-keycloak.amazingtech.vn/auth/realms/dev
minio:
  url: http://103.173.255.39:9001
  access:
    secret: mGUnihw7IeJ3C6EQ
    name: mGUnihw7IeJ3C6EQ
  buckek:
    name: requestformstudent

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always

# Keycloak settings
keycloak:
  realm: dev
  resource: admin-spring-boot
  app-client: employee-service
  auth-server-url: http://vuondau-keycloak.amazingtech.vn/auth
  credentials:
    secret: EJlhzOe84TZJhy41J3GhEg0yhaXzQuJL